FROM elasticsearch:5.6.16

RUN bin/elasticsearch-plugin install http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.6.16/elasticsearch-analysis-morphology-5.6.16.zip
